#!/bin/bash
RAJAPERF_DIR=$HOME/code/RAJAPerf
TUTKERNEL_DIR=$RAJAPERF_DIR/src/tutkernel
cp $TUTKERNEL_DIR/TUTORIAL_KERNEL.hpp.orig $TUTKERNEL_DIR/TUTORIAL_KERNEL.hpp
cp $TUTKERNEL_DIR/TUTORIAL_KERNEL.cpp.orig $TUTKERNEL_DIR/TUTORIAL_KERNEL.cpp
cp $TUTKERNEL_DIR/TUTORIAL_KERNEL-seq.orig $TUTKERNEL_DIR/TUTORIAL_KERNEL-seq.cpp
cp $TUTKERNEL_DIR/TUTORIAL_KERNEL-omp.cpp.orig $TUTKERNEL_DIR/TUTORIAL_KERNEL-omp.cpp