name: Container Build Matrices

on: 
  pull_request: []
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      is_empty: ${{ steps.matrix.outputs.is_empty }}
    steps:
    - uses: rse-ops/ci/uptodate/matrix@main
      id: matrix
      with:
        root: tutorials

  build:
    needs:
      - generate
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        result: ${{ fromJson(needs.generate.outputs.matrix) }}

    name: "Build ${{ matrix.result.container_name }}" 
    if: ${{ needs.generate.outputs.is_empty == 'false' }}
    steps:
    - name: Set Container Prefix
      env:
        repo: ${{ github.repository }}
      run: |
        # Split first by / to get org/repo
        repo_name=(${repo//// })
        # This is now just the repository
        repo_name=${repo_name[1]}      
        # Split again by -
        parts=(${repo_name//-/ })
        slug=${parts[0]}   
        echo "repo_name=${slug}" >> $GITHUB_ENV
        echo "Repository prefixed name is ${slug}"

    - uses: rse-ops/ci/uptodate/build@main
      with:
        repo: rse-ops
        registry: ghcr.io
        deploy: "${{ github.event_name != 'pull_request' }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        container_name: ${{ env.repo_name }}-${{ matrix.result.container_name }}
        command_prefix: ${{ matrix.result.command_prefix }}
        dockerfile: ${{ matrix.result.filename }}
